# Generated by Django 5.1 on 2024-08-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoloPuertasWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='clasificacion',
            field=models.CharField(max_length=10, verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
