# Generated by Django 5.1 on 2024-08-31 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SoloPuertasWeb', '0006_contacto_subscripcion_alter_clasificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscripcion',
            options={'verbose_name_plural': 'Subscripciones'},
        ),
    ]
